import PredictionCard from "./PredictionCard";

export default function PredictionRecents({ predictions = [] }) {
    return (
        <div
            className="
        rounded-3xl
        border
        border-[#35312C]
        bg-[#24211D]
        shadow-[0_10px_30px_rgba(0,0,0,.18)]
        h-[calc(100vh-90px)]
        flex
        flex-col
        overflow-hidden
    "
        >
            {/* Header */}

            <div className="px-7 py-6 border-b border-[#35312C]">

                <h2 className="text-2xl font-semibold text-[#ECE7DF]">
                    Prediction History
                </h2>

                <p className="mt-2 text-[#A79F95]">
                    Your latest AI analyses generated by your Digital Twin.
                </p>

            </div>

            {/* Cards */}

            <div
                className="
            flex-1
            overflow-y-auto
            p-6
            space-y-5
        "
            >
                {predictions.length ? (

                    predictions.map((prediction) => (

                        <PredictionCard
                            key={prediction.id}
                            prediction={prediction}
                        />

                    ))

                ) : (

                    <div className="h-full flex items-center justify-center">

                        <div className="text-center">

                            <div className="text-6xl mb-4">
                                📊
                            </div>

                            <h3 className="text-xl font-semibold text-[#ECE7DF]">
                                No Predictions Yet
                            </h3>

                            <p className="mt-2 text-[#A79F95] max-w-sm">
                                Generate your first IA prediction by filling out the
                                form. Your recent AI analyses will appear here.
                            </p>

                        </div>

                    </div>

                )}

            </div>

        </div>
    );
}